### ISSUE TITLE
[sdk] ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number

### ISSUE THREAD

**Issue by pablofiumara** [kubeflow/gcp-blueprints#390] opened 2022-09-15 00:21 UTC
### Environment

*  KFP version: 1.8.1
*  KFP SDK version: 1.6.2
*  All dependencies version:
kfp                          1.6.2
kfp-pipeline-spec            0.1.16
kfp-server-api               1.8.5

### Steps to reproduce
It happens on GCP, on a Kubeflow 1.5 cluster

To reproduce you should execute the following code:

```
from kfp import Client
kfp_client = Client(
    host="",
    client_id="",
    other_client_id="",
    other_client_secret="",
    namespace="aNamespace"
)

kfp_client.set_user_namespace(namespace="aNamespace")
pipeline_id = kfp_client.get_pipeline_id(name="aPipelineName")
print(pipeline_id)

```
### Expected result

I should get a pipeline id

Instead, I get

Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/user/.pyenv/versions/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/user/.pyenv/versions/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/user/.pyenv/versions/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/user/.pyenv/versions/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/user/.pyenv/versions/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/user/.pyenv/versions/3.9.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/user/.pyenv/versions/3.9.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/user/.pyenv/versions/3.9.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)

**Comment by gkcalat** [comment] 2022-09-15 17:45
Hi @pablofiumara!
where you able to create `kfp_client`? Can you share what you set as `host`?
Could you share what line results in the exception?
Do you have a pipeline with name `aPipelineName`?

**Comment by pablofiumara** [comment] 2022-09-15 20:43
Hi @gkcalat ! Thank you very much for your answer.

I was able to create a kfp_client. I set `https://cluster-name.endpoints.my-gcp-project.cloud.goog/pipeline` as host

The following line results in the exception

`pipeline_id = kfp_client.get_pipeline_id(name="aPipelineName")`

I have a pipeline with name `aPipelineName`

**Comment by gkcalat** [comment] 2022-09-15 21:37
@pablofiumara could you please repeat all steps share the full Traceback (all outputs)?

**Comment by pablofiumara** [comment] 2022-09-15 23:57
@gkcalat Thanks for your answer. Here's the full traceback

  File "/Users/user/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/user/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/user/src/stovell/project/src/stovell/kubeflow/pipelines/my-project/publish.py", line 44, in <module>
    pipeline_id = kfp_client.get_pipeline_id(name=PIPELINE_NAME)
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/kfp/_client.py", line 413, in get_pipeline_id
    result = self._pipelines_api.list_pipelines(filter=pipeline_filter)
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/kfp_server_api/api/pipeline_service_api.py", line 1212, in list_pipelines
    return self.list_pipelines_with_http_info(**kwargs)  # noqa: E501
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/kfp_server_api/api/pipeline_service_api.py", line 1313, in list_pipelines_with_http_info
    return self.api_client.call_api(
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/kfp_server_api/rest.py", line 208, in request
    r = self.pool_manager.request(method, url,
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/user/.pyenv/versions/project/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cluster-name.endpoints.gcp-project.cloud.goog', port=443): Max retries exceeded with url: /pipeline/apis/v1beta1/pipelines?filter=%7B%22predicates%22%3A+%5B%7B%22op%22%3A+1%2C+%22key%22%3A+%22name%22%2C+%22stringValue%22%3A+%22project+ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))
make: *** [publish] Error 1

**Comment by gkcalat** [comment] 2022-09-16 14:54
Thank you, @pablofiumara. It seems that the issue is unrelated to GCP distribution of Kubeflow. 
I am closing this as you have [another thread in pipelines repo](https://github.com/kubeflow/pipelines/issues/8267). Follow up over there.

**Closed by gkcalat** 2022-09-16 14:54 UTC
