### ISSUE TITLE
Upgrade ASM cause CVEs affected

### ISSUE THREAD

**Issue by kindomLee** [kubeflow/gcp-blueprints#367] opened 2022-06-14 08:10 UTC
We are experiencing CVE issues with the ASM(1.10) version we are currently using(kubeflow 1.5), and are wondering if there is a plan to update the update file as the upgrade file is outdated.
[kubeflow/asm/README.md](https://github.com/kubeflow/gcp-blueprints/blob/bef1ac8ddc42e708e55ac61d357619756e3b24b3/kubeflow/asm/README.md)

We also want to know if there are any other issues to be aware of if we upgrade ASM to 1.12 directly from the doc provided by Google.
https://cloud.google.com/service-mesh/v1.12/docs/unified-install/upgrade

**Comment by gkcalat** [comment] 2022-07-17 08:31
We have upgraded ASM to v1.13 in [Kubeflow 1.5.1 release](https://github.com/kubeflow/gcp-blueprints/releases/tag/v1.5.1). Please, see the [latest instructions in master branch](kubeflow/asm/README.md). If you wish to upgrade it yourself, please follow the [official instructions for ASM](https://cloud.google.com/service-mesh/v1.12/docs/upgrade-path-old-versions-gke).

**Comment by gkcalat** [comment] 2022-08-17 10:49
We are planning to upgrade ASM to 1.14 in KF 1.6.0. The master branch is now using ASM 1.13 and you can check it out. Given this, I am closing this issue. Let me know if the issue is still relevant.

**Closed by gkcalat** 2022-08-17 10:49 UTC
