### ISSUE TITLE
Stackdriver Logs are very expensive for kubeflow

### ISSUE THREAD

**Issue by nicokuzak** [kubeflow/gcp-blueprints#184] opened 2020-12-16 14:28 UTC
/kind bug

I upgraded to KF 1.2 on GCP and overnight had 116 GB of logging. 

**What did you expect to happen:**
Not having 116 GB. Seems to be some sort of cloud audit?

**Environment:**

- Kubeflow version: v1beta1 (1.2.0)
- kfctl version: (use `kfctl version`): None
- Kubernetes platform: GCP
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-dispatcher"
- OS (e.g. from `/etc/os-release`): Mac

**Comment by Bobgy** [comment] 2021-01-08 05:48
moving this, because it's gcp specific.
If I figured out it happens for everyone, I'll report another issue

**Comment by parthmishra** [comment] 2021-01-11 18:33
@Bobgy  I ran into this issue as well for 1.2 and checked the logging volume by pod and a significant amount was coming from `application-statefulset-0` in the container `management`. The log volume rate was a very hefty at around ~200 KiB/s so I immediately excluded the logs to avoid incurring a huge charge.

Not sure what the error exactly was, I'll see if I can find some sample logs and if not, attempt to reproduce them (I already uninstalled the cluster)

**Comment by Bobgy** [comment] 2021-01-14 12:03
I took a look at my instance, stackdriver cost is almost half of compute resources. That's indeed a big problem.

The application controller we deploy is: https://github.com/kubeflow/manifests/blob/master/application/application/base/stateful-set.yaml.
It seems upstream repo is https://github.com/kubernetes-sigs/application (there isn't much activity, the last commit on master was on Oct 17, 2020).

Logs look like
```
v1.RoleBinding/ml-pipeline-persistenceagent-binding
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.RoleBinding/kubeflow-pipelines-metadata-writer-binding
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.RoleBinding/ml-pipeline
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.RoleBinding/pipeline-runner-binding
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.RoleBinding/kubeflow-pipelines-cache-deployer-rolebinding
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.RoleBinding/ml-pipeline-viewer-crd-binding
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Service/kubeflow-pipelines-profile-controller
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Service/cache-server
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Service/ml-pipeline
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Service/ml-pipeline-ui
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Service/ml-pipeline-visualizationserver
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/pipeline-api-server-config-f4t72426kt
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/pipeline-upstream-install-config-d7hkh24mdg
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/kubeflow-pipelines-profile-controller-code-gd97t2m5f5
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/kubeflow-pipelines-profile-controller-env-5252m69c4c
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/kubeflow-pipelines-profile-controller-code-f22md76gd2
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/pipeline-install-config-2829cc67f8
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/ml-pipeline-ui-configmap
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/kubeflow-pipelines-profile-controller-env-mgh6th2gff
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/pipeline-upstream-install-config-486875c255
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/kubeflow-pipelines-profile-controller-env-822cf46mft
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/pipeline-api-server-config-dc9hkg52h6
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/pipeline-install-config-hb59bck49g
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.ConfigMap/pipeline-upstream-install-config-c958fm776d
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Secret/mysql-secret-fd5gktm75t
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Secret/mysql-secret-db2h2gbg52
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/ml-pipeline
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/ml-pipeline-viewer-crd
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/cache-deployer-deployment
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/kubeflow-pipelines-profile-controller
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/ml-pipeline-visualizationserver
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/ml-pipeline-scheduledworkflow
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/cache-server
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/ml-pipeline-ui
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/metadata-writer
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)   nochange: kubeflow/*v1.Deployment/ml-pipeline-persistenceagent
2021/01/14 12:01:31 *v1beta1.Application/kubeflow/kubeflow-pipelines(cmpnt:app)  } reconciling component
```
I think the correct fix is to change it to a higher log level, so it only shows warnings/errors.

That leads me to think... what's the value application CRs are bringing to us? As a developer, I almost never look at application CRs, because I know the low-level details. There doesn't seem to be enough UI/guidance that teach entrance level people to use them. Are they really useful in Kubeflow?

**Comment by parthmishra** [comment] 2021-01-14 20:50
Checked the controller logs and I was getting similar output to you. What do you think of an interim fix since it seems like changing the requirements for CR pattern is going to be a longer term discussion? The costs incurred by this sneakily flies underneath the radar. I'll keep excluding the logs via Logs Router since it doesn't seem like there's much useful diagnostic info coming from it.

**Comment by Bobgy** [comment] 2021-01-15 01:00
@parthmishra I think a quick workaround can be:
```
$ kubectl edit sts application-controller-stateful-set -n kubeflow

...
containers:
      command:
        - /bin/sh
        - -c
      - args:
        - |
          echo "logs are hidden because volume is too excessive" &&
          /root/manager 2> /dev/null
...
```
The functionality has nothing wrong, we just do not need the logs

**Comment by Bobgy** [comment] 2021-01-22 04:00
We can wait for manifest WG discussion, maybe we can drop kubernetes application altogether in the future.

**Comment by maorzalt** [comment] 2021-02-16 22:16
I have the same issue with kubeflow 1.0

Here's the YAML:
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"kubeflow","app.kubernetes.io/instance":"kubeflow-v1.0.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"kubeflow","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v1.0.0"},"name":"application-controller-stateful-set","namespace":"kubeflow"},"spec":{"selector":{"matchLabels":{"app":"application-controller","app.kubernetes.io/component":"kubeflow","app.kubernetes.io/instance":"kubeflow-v1.0.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"kubeflow","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v1.0.0"}},"serviceName":"application-controller-service","template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"labels":{"app":"application-controller","app.kubernetes.io/component":"kubeflow","app.kubernetes.io/instance":"kubeflow-v1.0.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"kubeflow","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v1.0.0"}},"spec":{"containers":[{"command":["/root/manager"],"env":[{"name":"project","value":"light-sunup-244111"}],"image":"gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta","imagePullPolicy":"Always","name":"manager"}],"serviceAccountName":"application-controller-service-account"}},"volumeClaimTemplates":[]}}
  creationTimestamp: "2021-01-09T19:55:23Z"
  generation: 7
  labels:
    app.kubernetes.io/component: kubeflow
    app.kubernetes.io/instance: kubeflow-v1.0.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: kubeflow
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v1.0.0
  name: application-controller-stateful-set
  namespace: kubeflow
  resourceVersion: "36520504"
  selfLink: /apis/apps/v1/namespaces/kubeflow/statefulsets/application-controller-stateful-set
  uid: 9c73b3a8-52b4-11eb-a0cc-42010a800088
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: application-controller
      app.kubernetes.io/component: kubeflow
      app.kubernetes.io/instance: kubeflow-v1.0.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: kubeflow
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v1.0.0
  serviceName: application-controller-service
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: application-controller
        app.kubernetes.io/component: kubeflow
        app.kubernetes.io/instance: kubeflow-v1.0.0
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: kubeflow
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: v1.0.0
    spec:
      containers:
      - command:
        - /root/manager
        env:
        - name: project
          value: light-sunup-244111
        image: gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta
        imagePullPolicy: Always
        name: manager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: application-controller-service-account
      serviceAccountName: application-controller-service-account
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: application-controller-stateful-set-6ff5c6b884
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updateRevision: application-controller-stateful-set-6ff5c6b884
  updatedReplicas: 1


I couldn't get @Bobgy 's modification to work.  Could you help me out?

**Comment by crmne** [comment] 2021-02-21 15:44
@maorzalt this should help you:

```
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - |
      echo "logs are hidden because volume is too excessive" &&
      /root/manager 2> /dev/null
```

**Comment by Bobgy** [comment] 2021-03-19 07:21
I am sending https://github.com/kubeflow/pipelines/pull/5336 to make K8s application optional for Kubeflow Pipelines. In upcoming releases, we should consider not include application by default.

**Closed** 2021-03-19 08:01 UTC
Labels: kind/bug

**Comment by fabito** [comment] 2021-05-12 10:52
This is what I used:

```bash
kubectl --context mycontext patch sts application-controller-stateful-set -n kubeflow --type json \
  -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/command", "value": [ "/bin/sh", "-c", "echo \"logs are hidden because volume is too excessive\" && /root/manager 2> /dev/null"]}]'
```

**Comment by susan-shu-c** [comment] 2021-06-29 13:34
I'm on Kubeflow v1.3 now and that doesn't work, after subbing in the correct context, of course - getting this`Error from server (NotFound): statefulsets.apps "application-controller-stateful-set" not found`

**Comment by susan-shu-c** [comment] 2021-06-29 13:52
Doing some more investigation, it seems that with v1.3, now it's 

```sh
kubectl --context gke_<mycontext> get sts metacontroller -n kubeflow -o yaml
```

(Unchanged version)
```yaml
  serviceName: ""
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: metacontroller
        kustomize.component: metacontroller
    spec:
      containers:
      - command:
        - /usr/bin/metacontroller
        - --logtostderr
        - -v=4
        - --discovery-interval=20s
        image: metacontroller/metacontroller:v0.3.0
        imagePullPolicy: Always
        name: metacontroller
        ports:
        - containerPort: 2345
```
