### ISSUE TITLE
Kubeflow manifests not compatible with kustomize 3.8.1; unknown field env

### ISSUE THREAD

**Issue by dwatrous** [kubeflow/gcp-blueprints#125] opened 2020-08-13 22:07 UTC
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

During the `make apply` step, I get the following error

```
kustomize build --load_restrictor none -o .build/kubeflow-apps ./instance/kustomize/kubeflow-apps
Error: accumulating resources: accumulateFile "accumulating resources from '../../../upstream/manifests/stacks/gcp': read /home/danielwatrous/kfdir/upstream/manifests/stacks/gcp: is a directory", accumulateDirector: "recursed accumulation of path '/home/danielwatrous/kfdir/upstream/manifests/stacks/gcp': accumulating resources: accumulateFile \"accumulating resources from '../../pipeline/installs/multi-user': read /home/danielwatrous/kfdir/upstream/manifests/pipeline/installs/multi-user: is a directory\", accumulateDirector: \"recursed accumulation of path '/home/danielwatrous/kfdir/upstream/manifests/pipeline/installs/multi-user': accumulating resources: accumulateFile \\\"accumulating resources from 'api-service': read /home/danielwatrous/kfdir/upstream/manifests/pipeline/installs/multi-user/api-service: is a directory\\\", accumulateDirector: \\\"couldn't make target for path '/home/danielwatrous/kfdir/upstream/manifests/pipeline/installs/multi-user/api-service': json: unknown field \\\\\\\"env\\\\\\\"\\\"\""
```

**Comment by dwatrous** [comment] 2020-08-13 22:24
I was using
ustomize version
{Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}

Using 3.2.1 works.

**Comment by nuel-d1** [comment] 2020-08-24 13:59
> @dwatrous What version of kustomize are you running?
> 
> Can you try version 3.2.1: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.2.1

How do i install version 3.2.1? I can't seem to find my way around it

**Comment by jlewi** [comment] 2020-08-29 01:10
Duplicate of kubeflow/manifests#538

**Comment by mnmami** [comment] 2020-12-01 14:58
For Kubeflow v1.2 I read:

> Note: Starting from Kubeflow v1.2, we fixed the compatibility problem with Kustomize v3.2.1+, so you can now install any Kustomize v3+, including the latest Kustomize versions.

Using that command I got Kustomize version 3.8.7 with which I got no issue creating the management cluster. However, I did get the error reported in this issue using that kustomize version while creating the managed cluster. So I had to roll back to Kustomize v3.2.1 to solve that issue.

**Comment by Bobgy** [comment] 2020-12-02 07:57
@mnmami Can you confirm your upstream manifests folder's version? I suspect some outdated instruction led you to still deploy KF v1.1, because GCP deploy instructions haven't been fully updated.

**Comment by mnmami** [comment] 2020-12-02 08:18
Ooh :( I got v1.1.0 `kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/kubeflow@v1.1.0 ./${KFDIR}`, indeed.

Will I be able to upgrade after you push the new upstream or I need to redo the deployment from scratch?

**Comment by Bobgy** [comment] 2020-12-02 09:38
@mnmami upgrade instructions are in above PR, you can refer to them or wait until the PR is merged.

Manifests for 1.2.0 is already ready

**Comment by mnmami** [comment] 2020-12-02 10:13
@Bobgy ok thanks for letting me know they are ready to be used already. Since I created the management cluster with v1.2 manifests, no upgrade is required there, right?

**Comment by Bobgy** [comment] 2020-12-02 10:16
@mnmami Yes, that's correct

**Comment by mnmami** [comment] 2020-12-02 15:21
Ok, great. I didb't upgrade. I actually deleted the cluster and recreated it again. The steps just worked. Just one remark. Here:

`KF_DIR=<path to your management cluster configuration directory>`

I think  "management" there is a typing mistake? It should be as you described just above:

`${KF_DIR} environment variable contains the path where you want to put your Kubeflow application directory`.

Looking forward to the updated docs.

**Comment by sunilfernandes** [comment] 2021-01-15 16:39
@Bobgy This is still throwing an error with latest kustomize versions. I tried with 3.9.1 and as suggested by you above version  3.8.7 too but was getting the same issues.

`kustomize build --load_restrictor none -o .build/kubeflow-apps ./instance/kustomize/kubeflow-apps
Error: accumulating resources: 2 errors occurred:
        * accumulateFile error: "accumulating resources from '../../../upstream/manifests/stacks/gcp': read /home/jupyter/kubeflow/kf12install/kubeflow/upstream/manifests/stacks/gcp: is a directory"
        * accumulateDirector error: "recursed accumulation of path '/home/jupyter/kubeflow/kf12install/kubeflow/upstream/manifests/stacks/gcp': accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from '../../pipeline/installs/multi-user': read /home/jupyter/kubeflow/kf12install/kubeflow/upstream/manifests/pipeline/installs/multi-user: is a directory\"\n\t* accumulateDirector error: \"recursed accumulation of path '/home/jupyter/kubeflow/kf12install/kubeflow/upstream/manifests/pipeline/installs/multi-user': accumulating resources: 2 errors occurred:\\n\\t* accumulateFile error: \\\"accumulating resources from 'api-service': read /home/jupyter/kubeflow/kf12install/kubeflow/upstream/manifests/pipeline/installs/multi-user/api-service: is a directory\\\"\\n\\t* accumulateDirector error: \\\"couldn't make target for path '/home/jupyter/kubeflow/kf12install/kubeflow/upstream/manifests/pipeline/installs/multi-user/api-service': json: unknown field \\\\\\\"env\\\\\\\"\\\"\\n\\n\"\n\n"`

Downgraded to 3.2.1 and it works for me now, I would recommend the official documentation be updated.

**Comment by Bobgy** [comment] 2021-01-17 01:21
@sunilfernandes which platform did you deploy to? Is it GCP and 1.2.0?

**Comment by sunilfernandes** [comment] 2021-01-18 09:43
> @sunilfernandes which platform did you deploy to? Is it GCP and 1.2.0?

Yes to both questions @Bobgy

**Comment by Bobgy** [comment] 2021-01-20 09:27
Thanks for the report!
Let me try to reproduce.

**Comment by Bobgy** [comment] 2021-01-23 06:59
@sunilfernandes I tried again and verified everything still works with Kustomize v3.8.7.
Your error message looks weird because `kubeflow/upstream/manifests/pipeline/installs/multi-user/api-service/kustomization.yaml` should only contain `envs` field, but not `env` field.
You can check the source code: https://github.com/kubeflow/manifests/blob/da561762dde5ef8e70ed27aa028b61711c1c4231/pipeline/installs/multi-user/api-service/kustomization.yaml#L8.

So I'm suspecting something went wrong and you got an outdated version.
Can you confirm your `kubeflow/upstream/manfiests/Kptfile`?
It should be of the following content:
```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: dev-1-23
upstream:
  type: git
  git:
    commit: da561762dde5ef8e70ed27aa028b61711c1c4231
    repo: https://github.com/kubeflow/manifests
    directory: /
    ref: v1.2.0
```

Note, `ref: v1.2.0` which shows its version.

**Comment by Bobgy** [comment] 2021-02-26 06:30
Not getting further response, I assume the problem is solved.
Feel free to comment more if you still have any questions.

**Closed by Bobgy** 2021-02-26 06:30 UTC
Labels: area/docs, kind/bug, platform/gcp
